spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://sql7.freesqldatabase.com:3306/sql7610279
    username: sql7610279
    password: DsPHSVy29q
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 10
        format_sql: true
jwt:
  token:
    secret: 244226452948404D635166546A576E5A7234753778214125442A462D4A614E64